# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        ('account', '0001_initial'),
        ('subscription', '0002_auto_20170815_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('profile', 'period')]),
        ),
    ]
